# Generated by Django 3.2.7 on 2021-09-22 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('min_age', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=64)),
                ('created', models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 22, 8, 41, 27, 830514))),
                ('image', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
    ]
